### ISSUE TITLE
Incessant error message: "Download failed. Please check your connection." despite no connection issues.

### ISSUE THREAD

**Issue by DomD48** [jscher2000/I-Hate-Tabs---SDI-extension#1]
When trying to add extension "I Hate Tabs - SDI", the error message "Download failed. Please check your connection." appears incessantly, despite no connection issues whatsoever:

https://addons.mozilla.org/en-US/firefox/addon/i-hate-tabs-sdi-for-firefox/

The issue occurred at ~10:00 am ET on date 2019/05/04.

**Comment by jscher2000** [comment]
Hi DomD48, as you probably discovered by now, there was a general problem with a certificate used to verify extensions that affected many (most?) of them and you need to install a hotfix for Firefox to be able to run, install, or update them. 

https://support.mozilla.org/kb/add-ons-disabled-or-fail-to-install-firefox

**Comment by DomD48** [comment]
Already installed, enabled, and configured the hotfix, as well as all the other temporary "solutions". Despite them all, the issue has persisted for 2 days.

**Comment by jscher2000** [comment]
Hi DomD48, what version of Firefox?

It sounds as though the hotfix did not install the new certificate successfully. You can check on the Options/Preferences page:

* Windows: "3-bar" menu button (or Tools menu) > Options
* Mac: "3-bar" menu button (or Firefox menu) > Preferences
* Linux: "3-bar" menu button (or Edit menu) > Preferences
* Any system: type or paste '''about:preferences''' into the address bar and press Enter/Return to load it

In Firefox 56+, the search box at the top of the page, type ''cert'' and Firefox should filter to the **Certificates** section, where you can click the "View Certificates" button.

(Before Firefox 56, click Advanced in the left column, and Cetificates in the right column, then click the "View Certificates" button.)

In the Certificate Manager dialog, check the Authorities tab for a Mozilla Corporation section of the list:

![Screenshot of Certificate Manager showing new certificate](https://prod-cdn.sumo.mozilla.net/uploads/images/2019-05-04-21-46-07-6b23a7.png)

Can you find that cert?

**Comment by DomD48** [comment]
No I cannot. In fact, there are no certificates from "Mozilla Corporation" under the "Authorities" tab.

**Comment by jscher2000** [comment]
Okay, Firefox 66.0.4 and Firefox 60.6.2esr have been released. If you are running either the Firefox 66 (release) version or Firefox 60 ESR, that should solve it. If you have a different version, what version is it?

**Comment by DomD48** [comment]
Quantum 57.0.4 (64-bit).

**Comment by jscher2000** [comment]
> Quantum 57.0.4 (64-bit).

Why only 57? It would be easiest to update to a current release. If you cannot update, you still need the new certificate in order for your Firefox to be able to verify extension signatures. Mozilla may release a hotfix for non-supported versions of Firefox but I have not heard an announcement yet. These are the channels being used recently:

* https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
* https://twitter.com/mozamo

If you want an unsupported approach, check my post for Firefox 52 ESR users: https://support.mozilla.org/questions/1258165#answer-1218833

**Comment by DomD48** [comment]
"Why only 57?"

Because forced updates, and high-maintenance software is the reason I stopped using other browsers. Now, it seems I have to switch to something else.

**Comment by jscher2000** [comment]
The ESR track is perhaps the best fit for you: https://support.mozilla.org/kb/switch-to-firefox-extended-support-release-esr

Anyway, if you insist on using 57, you can try the workaround.

**Comment by DomD48** [comment]
I don't insist on doing anything. I'm just tired of playing all the cat-and-mouse games.

**Comment by jscher2000** [comment]
Since there's nothing I can do about the expired certificate problem, I'm going to close this issue.

**Comment by DomD48** [comment]
Okay. Thanks, anyway.

For reference purposes: as of the time of writing this comment, the "Download failed. Please check your connection." error persists without resolution.
