### ISSUE TITLE
Need "manially re-enable" for functioning

### ISSUE THREAD

**Issue by piyavking** [jscher2000/I-Hate-Tabs---SDI-extension#2]
I launch firefox (102.8.0esr), and add-on only start functioning if I manually turn them off and on again in the add-on manager...

**Comment by jscher2000** [comment]
Hi, I don't actually use this extension so I have not been keeping up with how it has been (not) working in recent years.

I cannot replicate the problem on Firefox 109 on Windows. I don't know whether I will install Firefox 102esr for testing. In the past, trying to have both ESR and regular Firefox broke various icons/defaults every time either of them updated, so I have been trying to avoid it...

**Comment by piyavking** [comment]
Problem disappears when i'm delete file 'compatibility.ini' in my profile, I "frozen" it by creating write-protected empty compatibility.ini. Thanks for feedback!

**Comment by jscher2000** [comment]
Hmm, that's strange. Hopefully you don't have two different versions of Firefox trying to use the same profile folder. That definitely will create problems for the older version.

I don't think I'm going to be able to resolve this one, so I'm closing it.
